[phases.setup]
nixPkgs = ['python3', 'postgresql', 'gcc', 'nodejs', 'npm']

[phases.install]
cmds = [
    'python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt',
    'npm --prefix frontend install',
    'npm --prefix frontend run build',
    'mkdir -p backend/static',
    'cp -r frontend/build/* backend/static/'
]
