[build]
builder = "nixpacks"
buildCommand = "sh ./build.sh"

[deploy]
startCommand = "sh ./start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[deploy.envs]
FLASK_ENV = "production"
