[build]
builder = "nixpacks"
buildCommand = "sh ./build.sh"

[deploy]
startCommand = "sh ./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"

[deploy.envs]
FLASK_ENV = "production"
PORT = "8080"
